#!/usr/bin/env python3
"""Compile agents/<id>.md into a typed hop module.

Markdown stays the source of truth. Generated code only encodes:
- path to the agent file
- frontmatter metadata
- legal next-hop union from the Next agents table

Usage:
  python3 hosts/compile_agent_hop.py agents/evaluator.md
  python3 hosts/compile_agent_hop.py --check agents/evaluator.md
  python3 hosts/compile_agent_hop.py --all
  python3 hosts/compile_agent_hop.py --check --all

The next-agent id `idle` means stop (no further specialty hop).
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GEN_DIR = Path(__file__).resolve().parent / "generated"


def parse_frontmatter(text: str) -> dict[str, str]:
    if not text.startswith("---\n"):
        raise ValueError("missing YAML frontmatter")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise ValueError("unclosed frontmatter")
    meta: dict[str, str] = {}
    for line in text[4:end].splitlines():
        if not line.strip() or line.strip().startswith("#"):
            continue
        if ":" not in line:
            continue
        key, val = line.split(":", 1)
        meta[key.strip()] = val.strip().strip('"').strip("'")
    return meta


def parse_next_agents(text: str) -> list[tuple[str, str, str]]:
    """Return list of (kind, agent_id, when)."""
    m = re.search(r"## Next agents\n+(.*?)(?:\n## |\nAgent file contract:|\Z)", text, re.S)
    if not m:
        raise ValueError("missing ## Next agents section")
    block = m.group(1)
    rows: list[tuple[str, str, str]] = []
    for line in block.splitlines():
        line = line.strip()
        if not line.startswith("|"):
            continue
        cols = [c.strip() for c in line.strip("|").split("|")]
        if len(cols) < 3:
            continue
        kind, agent, when = cols[0], cols[1], cols[2]
        if kind.lower() == "kind" or set(kind) <= {"-", ":"}:
            continue
        # strip backticks; take first token ("intake / idle" → intake)
        agent = agent.strip("`")
        agent = agent.split()[0] if agent else agent
        # "(idle)" → idle sentinel (stop hop)
        if agent in {"(idle)", "idle"}:
            agent = "idle"
        if not re.fullmatch(r"[a-z][a-z0-9-]*", agent):
            continue
        rows.append((kind, agent, when))
    if not rows:
        raise ValueError("no next-agent rows parsed")
    return rows


def content_hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]


def py_literal_union(agents: list[str]) -> str:
    return " | ".join(f'Literal["{a}"]' for a in agents)


def ts_union(agents: list[str]) -> str:
    return " | ".join(f'"{a}"' for a in agents)


def pascal(agent_id: str) -> str:
    return "".join(p.capitalize() for p in agent_id.split("-"))


def render_python(rel_path: str, meta: dict[str, str], edges: list[tuple[str, str, str]], digest: str) -> str:
    agent_id = meta["id"]
    agents = []
    for _, a, _ in edges:
        if a not in agents:
            agents.append(a)
    edges_py = ",\n    ".join(
        f'HopEdge(kind="{k}", agent="{a}", when={when!r})' for k, a, when in edges
    )
    heuer = meta.get("heuer_lines", "[]")
    return f'''\
# AUTO-GENERATED by hosts/compile_agent_hop.py — do not edit.
# Source of truth: {rel_path}
# source_sha256_16={digest}

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal

AGENT_ID = "{agent_id}"
AGENT_REL_PATH = "{rel_path}"
DESCRIPTION = {meta.get("description", "")!r}
MODEL_CLASS = {meta.get("model_class", "")!r}
HEUER_LINES_RAW = {heuer!r}
SOURCE_SHA256_16 = "{digest}"

REPO_ROOT = Path(__file__).resolve().parents[2]
AGENT_PATH = REPO_ROOT / AGENT_REL_PATH

NextAgent = {py_literal_union(agents)}
LegalNext = NextAgent  # alias


@dataclass(frozen=True)
class HopEdge:
    kind: str
    agent: str
    when: str


LEGAL_EDGES: tuple[HopEdge, ...] = (
    {edges_py},
)

LEGAL_NEXT: frozenset[str] = frozenset(e.agent for e in LEGAL_EDGES)


@dataclass
class NextHop:
    """Typed next step after this agent finishes."""

    next_agent: NextAgent
    kind: Literal["default_next", "consult", "reentry"]
    reason: str = ""


def load_prompt() -> str:
    """Load the owned prompt. Markdown remains editable source of truth."""
    return AGENT_PATH.read_text(encoding="utf-8")


def build_user_payload(state: dict[str, Any]) -> dict[str, Any]:
    """Pass only fields this hop should see (required inputs)."""
    return {{
        "hypotheses": state.get("hypotheses"),
        "evidence": state.get("evidence"),
        "assumptions": state.get("assumptions"),
        "matrix": state.get("matrix"),
        "open_collection": state.get("open_collection"),
    }}


def build_messages(state: dict[str, Any]) -> list[dict[str, str]]:
    """Factor-2 style messages: owned system prompt + structured user state."""
    import json

    return [
        {{"role": "system", "content": load_prompt()}},
        {{
            "role": "user",
            "content": (
                "Run this agent hop.\\n"
                "Write only the state fields this agent owns.\\n"
                "When verify passes, choose next_agent from LEGAL_NEXT.\\n"
                "LEGAL_NEXT=" + json.dumps(sorted(LEGAL_NEXT)) + "\\n\\n"
                "analysis_state (inputs):\\n"
                + json.dumps(build_user_payload(state), indent=2, default=str)
            ),
        }},
    ]


def parse_next_hop(data: dict[str, Any]) -> NextHop:
    """Validate LLM structured output against the legal edge union."""
    agent = data.get("next_agent")
    kind = data.get("kind") or "default_next"
    reason = str(data.get("reason") or "")
    if agent not in LEGAL_NEXT:
        raise ValueError(
            f"illegal next_agent {{agent!r}}; legal={{sorted(LEGAL_NEXT)}}"
        )
    if kind not in {{"default_next", "consult", "reentry"}}:
        raise ValueError(f"illegal kind {{kind!r}}")
    allowed_kinds = {{e.kind for e in LEGAL_EDGES if e.agent == agent}}
    if kind not in allowed_kinds:
        raise ValueError(
            f"kind {{kind!r}} not allowed for {{agent!r}}; allowed={{sorted(allowed_kinds)}}"
        )
    return NextHop(next_agent=agent, kind=kind, reason=reason)  # type: ignore[arg-type]


def default_next() -> NextHop:
    for e in LEGAL_EDGES:
        if e.kind == "default_next":
            return NextHop(next_agent=e.agent, kind="default_next", reason=e.when)  # type: ignore[arg-type]
    raise RuntimeError("no default_next edge in source agent file")
'''


def render_typescript(rel_path: str, meta: dict[str, str], edges: list[tuple[str, str, str]], digest: str) -> str:
    agent_id = meta["id"]
    agents = []
    for _, a, _ in edges:
        if a not in agents:
            agents.append(a)
    edge_objs = ",\n  ".join(
        f'{{ kind: "{k}", agent: "{a}", when: {json_str(when)} }}' for k, a, when in edges
    )
    return f'''\
// AUTO-GENERATED by hosts/compile_agent_hop.py — do not edit.
// Source of truth: {rel_path}
// source_sha256_16={digest}

export const AGENT_ID = "{agent_id}" as const;
export const AGENT_REL_PATH = "{rel_path}" as const;
export const DESCRIPTION = {json_str(meta.get("description", ""))};
export const MODEL_CLASS = {json_str(meta.get("model_class", ""))};
export const SOURCE_SHA256_16 = "{digest}" as const;

export type NextAgent = {ts_union(agents)};
export type HopKind = "default_next" | "consult" | "reentry";

export type HopEdge = {{ kind: HopKind | string; agent: NextAgent; when: string }};

export const LEGAL_EDGES: readonly HopEdge[] = [
  {edge_objs},
] as const;

export const LEGAL_NEXT: readonly NextAgent[] = [
  {", ".join(json_str(a) for a in agents)},
] as const;

export type NextHop = {{
  next_agent: NextAgent;
  kind: HopKind;
  reason?: string;
}};

/** Load owned prompt from repo (Node). Markdown is source of truth. */
export async function loadPrompt(repoRoot: string): Promise<string> {{
  const fs = await import("node:fs/promises");
  const path = await import("node:path");
  return fs.readFile(path.join(repoRoot, AGENT_REL_PATH), "utf8");
}}

export function assertLegalNext(hop: NextHop): NextHop {{
  if (!LEGAL_NEXT.includes(hop.next_agent)) {{
    throw new Error(`illegal next_agent ${{hop.next_agent}}`);
  }}
  const kinds = LEGAL_EDGES.filter((e) => e.agent === hop.next_agent).map((e) => e.kind);
  if (!kinds.includes(hop.kind)) {{
    throw new Error(`kind ${{hop.kind}} not allowed for ${{hop.next_agent}}`);
  }}
  return hop;
}}

/** Factor-2 sketch: system = full agent markdown; user = required state JSON. */
export async function buildMessages(
  repoRoot: string,
  state: Record<string, unknown>,
): Promise<Array<{{ role: "system" | "user"; content: string }}>> {{
  const system = await loadPrompt(repoRoot);
  const payload = {{
    hypotheses: state.hypotheses,
    evidence: state.evidence,
    assumptions: state.assumptions,
    matrix: state.matrix,
    open_collection: state.open_collection,
  }};
  return [
    {{ role: "system", content: system }},
    {{
      role: "user",
      content:
        "Run this agent hop.\\n" +
        "Write only the state fields this agent owns.\\n" +
        "When verify passes, choose next_agent from LEGAL_NEXT.\\n" +
        `LEGAL_NEXT=${{JSON.stringify(LEGAL_NEXT)}}\\n\\n` +
        `analysis_state (inputs):\\n${{JSON.stringify(payload, null, 2)}}`,
    }},
  ];
}}
'''


def json_str(s: str) -> str:
    import json

    return json.dumps(s)


def compile_agent(agent_path: Path) -> tuple[Path, Path, str]:
    text = agent_path.read_text(encoding="utf-8")
    meta = parse_frontmatter(text)
    if "id" not in meta:
        raise ValueError("frontmatter missing id")
    edges = parse_next_agents(text)
    digest = content_hash(text)
    try:
        rel = str(agent_path.resolve().relative_to(ROOT))
    except ValueError:
        rel = str(agent_path)

    GEN_DIR.mkdir(parents=True, exist_ok=True)
    py_path = GEN_DIR / f"{meta['id'].replace('-', '_')}_hop.py"
    ts_path = GEN_DIR / f"{meta['id'].replace('-', '_')}_hop.ts"
    py_path.write_text(render_python(rel, meta, edges, digest), encoding="utf-8")
    ts_path.write_text(render_typescript(rel, meta, edges, digest), encoding="utf-8")
    return py_path, ts_path, digest


def check_fresh(agent_path: Path) -> int:
    text = agent_path.read_text(encoding="utf-8")
    meta = parse_frontmatter(text)
    digest = content_hash(text)
    py_path = GEN_DIR / f"{meta['id'].replace('-', '_')}_hop.py"
    if not py_path.exists():
        print(f"missing generated file: {py_path}", file=sys.stderr)
        return 1
    gen = py_path.read_text(encoding="utf-8")
    m = re.search(r"source_sha256_16=([0-9a-f]+)", gen)
    if not m or m.group(1) != digest:
        print(f"stale: {py_path} (re-run compile)", file=sys.stderr)
        return 1
    print(f"ok: {py_path} matches {agent_path}")
    return 0


def iter_agent_files() -> list[Path]:
    agents_dir = ROOT / "agents"
    out: list[Path] = []
    for path in sorted(agents_dir.glob("*.md")):
        if path.name == "README.md":
            continue
        text = path.read_text(encoding="utf-8")
        try:
            meta = parse_frontmatter(text)
        except ValueError:
            continue
        if "id" not in meta:
            continue
        out.append(path)
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "agent_md",
        type=Path,
        nargs="?",
        help="path to agents/<id>.md (omit with --all)",
    )
    ap.add_argument("--all", action="store_true", help="compile or check every agents/*.md with id")
    ap.add_argument("--check", action="store_true", help="verify generated hop is fresh")
    args = ap.parse_args()

    if args.all:
        paths = iter_agent_files()
        if not paths:
            print("no agent files found", file=sys.stderr)
            return 1
        rc = 0
        for path in paths:
            try:
                if args.check:
                    rc = max(rc, check_fresh(path))
                else:
                    py_path, ts_path, digest = compile_agent(path)
                    print(f"wrote {py_path}")
                    print(f"wrote {ts_path}")
                    print(f"source_sha256_16={digest}")
            except Exception as exc:  # noqa: BLE001 — report per file, keep going
                print(f"error: {path}: {exc}", file=sys.stderr)
                rc = 1
        return rc

    if args.agent_md is None:
        ap.error("agent_md is required unless --all is set")
    path = args.agent_md
    if not path.is_absolute():
        path = (Path.cwd() / path).resolve()
    if args.check:
        return check_fresh(path)
    py_path, ts_path, digest = compile_agent(path)
    print(f"wrote {py_path}")
    print(f"wrote {ts_path}")
    print(f"source_sha256_16={digest}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
